apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
spec:
  channel: stable-4.20
  desiredUpdate:
    version: 4.20.19
    image: "quay.io/openshift-release-dev/dev-release@sha256:e37bcdba07c7312607363ddf5a8e317e4b6952b1465704b38c9a081d095697be"
