apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
spec:
  channel: stable-4.20
  desiredUpdate:
    version: 4.20.0-0.ci-2026-04-26-081042
    image: "quay.io/openshift-release-dev/dev-release@sha256:1cc97e020b05a2ac0e2824345577137cd28f0eb229b7c096effe55902b9b4c1a"
