apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: x240m5-12
  namespace: ocp-edge1-cl4
  labels:
    infraenvs.agent-install.openshift.io: ocp-edge1-cl4
spec:
  config:
    # Removed the 'networkConfig' wrapper
    dns-resolver:
      config:
        server:
          - 10.46.57.1
    interfaces:
      - name: eno1
        type: ethernet
        state: up
        mac-address: "52:54:00:ca:c0:d5"
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          dhcp: true
          enabled: false
  interfaces:
    - name: eno1
      macAddress: "52:54:00:ca:c0:d5"
