apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: master-2.ocp-edge1-cl4.lab.eng.tlv2.redhat.com
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/cluster-reference: ocp-edge1-cl4/ocp-edge1-cl4
    bmac.agent-install.openshift.io/remove-agent-and-node-on-delete: true
  labels:
    infraenvs.agent-install.openshift.io: ocp-edge1-cl4
    cluster-name: ocp-edge1-cl4
  name: x240m5-13
spec:
  automatedCleaningMode: metadata
  bmc:
    address: "redfish-virtualmedia+https://ocp-edge12.lab.eng.tlv2.redhat.com:8000/redfish/v1/Systems/6d7dd058-311c-4709-89ef-e956b42d6e20"
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  bootMACAddress: 52:54:00:90:9d:4b
  online: true