apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/openshift-config/olm-patch.yaml
  - ../../../../components/openshift-config/admin-role-binding.yaml
  - ../../../../components/openshift-config/admin-group.yaml
  - ../../../../components/openshift-config/ingress-controller-patch.yaml
  - ./console-patch.yaml
  - ./oauth.yaml
  - ./cluster-version.yaml
