apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  labels:
    kubernetes.io/metadata.name: minio-operator
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
